CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) DEFAULT NULL,
    email VARCHAR(180) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    father_name VARCHAR(180) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    gender VARCHAR(20) DEFAULT NULL,
    blood_group VARCHAR(10) DEFAULT NULL,
    aadhaar VARCHAR(20) DEFAULT NULL,
    phone VARCHAR(20) NOT NULL,
    mobile_alt VARCHAR(20) DEFAULT NULL,
    email VARCHAR(180) DEFAULT NULL,
    address TEXT DEFAULT NULL,
    qualification VARCHAR(180) DEFAULT NULL,
    designation VARCHAR(180) DEFAULT NULL,
    registration_number VARCHAR(120) DEFAULT NULL,
    experience VARCHAR(50) DEFAULT NULL,
    employee_id VARCHAR(120) DEFAULT NULL,
    district VARCHAR(150) DEFAULT NULL,
    mandal VARCHAR(150) DEFAULT NULL,
    village VARCHAR(150) DEFAULT NULL,
    hospital VARCHAR(200) DEFAULT NULL,
    department VARCHAR(150) DEFAULT NULL,
    shift_type VARCHAR(50) DEFAULT NULL,
    joining_date DATE DEFAULT NULL,
    expiry_date DATE DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'active',
    role VARCHAR(120) DEFAULT NULL,
    photo VARCHAR(255) DEFAULT NULL,
    signature VARCHAR(255) DEFAULT NULL,
    documents VARCHAR(255) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS complaints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) DEFAULT 'Anonymous',
    district VARCHAR(150) NOT NULL,
    issue VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) DEFAULT 'pending',
    priority VARCHAR(20) DEFAULT 'Medium',
    reply_text TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS districts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    district_name VARCHAR(160) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_uploads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    media_type VARCHAR(40) NOT NULL,
    title VARCHAR(180) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    status VARCHAR(20) DEFAULT 'active',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT DEFAULT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO admins (username, password, full_name, email)
SELECT 'admin', '$2y$10$9gAFmBvQ7y3M5h8QnS7U0eLk9X5V9J8f83b0NOY1Q6J9U0iYBxQ4G', 'APCSNSC Administrator', 'admin@APCSNSC.local'
WHERE NOT EXISTS (SELECT 1 FROM admins WHERE username = 'admin');
